version: "3.7"

services:
  tautulli:
    image: lscr.io/linuxserver/tautulli
    container_name: tautulli
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${DOCKER_TZ}
    volumes:
      - ${CONFIG_LOCATION}/tautulli:/config
    labels:
      - "traefik.enable=true"
      - "traefik.port=8181"
      - "traefik.backend=tautulli"
      - "traefik.docker.network=main"
      - "traefik.frontend.entryPoints=http,https"
      - "traefik.frontend.rule=Host:tautulli.${DOMAIN_URL}"
      - traefik.frontend.auth.forward.address=${OAUTH_FORWARD_URL}
      - traefik.frontend.auth.forward.authResponseHeaders=X-Forwarded-User
      - traefik.frontend.auth.forward.trustForwardHeader=true
    restart: unless-stopped