version: '3.3'

services:
  logio-harvester:
    image: blacklabelops/logio
    container_name: harvester
    command: harvester
    user: root
    environment:
      - "LOGIO_HARVESTER_MASTER_HOST=${LOGIO_MASTER_HOST}"
      - "LOGIO_HARVESTER_MASTER_PORT=443"
      - 'DELAYED_START=30'
      - 'LOGIO_HARVESTER_NODENAME=DockerLogs-${DOMAIN_URL}'
      - 'LOGIO_HARVESTER_STREAMNAME=UnifiedLogs-${DOMAIN_URL}'
      - "LOG_FILE_PATTERN=*-json.log"
      - "LOGS_DIRECTORIES=/var/lib/docker/containers"
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers
      - /var/run/docker.sock:/var/run/docker.sock:ro
