version: '2'

services:
  logio:
    image: blacklabelops/logio
    restart: unless-stopped
    container_name: logio
    environment:
      LOGIO_ADMIN_USER: admin
      LOGIO_ADMIN_PASSWORD: ${LOGIO_ADMIN_PASSWORD}
    networks:
      - main
    labels:
      - "traefik.docker.network=main"
      - "traefik.enable=true"
      - "traefik.basic.frontend.rule=Host:logs.${DOMAIN_URL}"
      - "traefik.basic.port=28778"
      - "traefik.frontend.entryPoints=http,https"

  logio-harvester:
    image: blacklabelops/logio
    container_name: logio-harvester
    user: root
    command: harvester
    environment:
      LOG_FILE_PATTERN: '*-json.log'
      LOGS_DIRECTORIES: '/var/lib/docker/containers'
    volumes:
      - ${DOCKER_LOCATION}/containers:/var/lib/docker/containers
    networks:
      - main

networks: 
  main:
    external: true