version: "2"
services:
  resilio-sync:
    image: linuxserver/resilio-sync
    container_name: resilio-sync
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Argentina/Buenos_Aires
      - UMASK_SET=<022>
    volumes:
      - ${CONFIG_LOCATION}/resilio:/config
      - ${RESILIO_DOWNLOADS}:/downloads
      - ${RESILIO_HOME}:/sync
    ports:
      - 8888:8888
      - 55555:55555
    restart: unless-stopped
    networks:
      - main

networks:
  main:
    external: true