version: "3"

# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "8000:80"
      - "8001:443"
    environment:
      TZ: 'America/Argentina/Buenos_Aires'
      WEBPASSWORD: ${PIHOLE_PASSWORD}
      ServerIP: 192.168.1.23
      VIRTUAL_HOST: pihole.papini.dantebarba.com.ar
      VIRTUAL_PORT: 80
    volumes:
       - '${CONFIG_LOCATION}/pihole/pihole:/etc/pihole/'
       - '${CONFIG_LOCATION}/pihole/dnsmasq.d:/etc/dnsmasq.d/'
    dns:
      - 127.0.0.1
      - 1.1.1.1
    # Recommended but not required (DHCP needs NET_ADMIN)
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    restart: unless-stopped
    labels:
      - "traefik.docker.network=main"
      - "traefik.enable=true"
      - "traefik.basic.frontend.rule=Host:pihole.${DOMAIN_URL}"
      - "traefik.basic.port=80,443"
      - "traefik.frontend.entryPoints=http,https"
    networks:
      - main

networks: 
  main:
    external: true