version: '2'

services:
  movies-downstream:
    image: pfidr/rclone:latest
    container_name: movies-downstream
    restart: unless-stopped
    volumes:
      - "${STORAGE_LOCATION}/radarr/movies/local:/destination"
      - "${CONFIG_LOCATION}/rclone:/config"
      - "${CONFIG_LOCATION}/rclone/ssh:/.ssh:ro"
      - "${CONFIG_LOCATION}/rclone/logs_movies:/tmp/"
    environment:
      SYNC_SRC: Crown:${REMOTE_STORAGE_LOCATION}/radarr/movies/local
      SYNC_DEST: /destination
      SYNC_OPTS: '-v --min-age ${MIN_AGE} --delete-empty-src-dirs'
      CHECK_URL: ${MOVIES_CHECK_URL}
      RCLONE_DIR_CHECK_SKIP: 'true'
      RCLONE_CMD: move
      FORCE_SYNC: ${FORCE_SYNC}
      TZ: 'America/Argentina/Buenos_Aires'
      CRON: '0 3 * * *'
      CRON_ABORT: '0 10 * * *'
      UID: ${PUID}
      GID: ${PGID}
    networks:
      - main

  series-downstream:
    image: pfidr/rclone:latest
    container_name: series-downstream
    restart: unless-stopped
    volumes:
      - "${STORAGE_LOCATION}/sonarr/tvseries:/destination"
      - "${CONFIG_LOCATION}/rclone:/config"
      - "${CONFIG_LOCATION}/rclone/ssh:/.ssh:ro"
      - "${CONFIG_LOCATION}/rclone/logs_series:/tmp/"
    environment:
      SYNC_SRC: Crown:${REMOTE_STORAGE_LOCATION}/sonarr/tvseries
      SYNC_DEST: /destination
      SYNC_OPTS: '-v --min-age ${MIN_AGE} --delete-empty-src-dirs'
      CHECK_URL: ${SERIES_CHECK_URL}
      RCLONE_DIR_CHECK_SKIP: 'true'
      RCLONE_CMD: move
      TZ: 'America/Argentina/Buenos_Aires'
      CRON: '0 3 * * *'
      CRON_ABORT: '0 10 * * *'
      UID: ${PUID}
      GID: ${PGID}
      FORCE_SYNC: ${FORCE_SYNC}
    networks:
      - main

  music-downstream:
    image: pfidr/rclone:latest
    container_name: music-downstream
    restart: unless-stopped
    volumes:
      - "${STORAGE_LOCATION}/deezldr/music:/destination"
      - "${CONFIG_LOCATION}/rclone:/config"
      - "${CONFIG_LOCATION}/rclone/ssh:/.ssh:ro"
      - "${CONFIG_LOCATION}/rclone/logs_music:/tmp/"
    environment:
      SYNC_SRC: Crown:${REMOTE_STORAGE_LOCATION}/deezldr/music
      SYNC_DEST: /destination
      SYNC_OPTS: '-v --min-age ${MIN_AGE} --delete-empty-src-dirs'
      RCLONE_DIR_CHECK_SKIP: 'true'
      CHECK_URL: ${MUSIC_CHECK_URL}
      RCLONE_CMD: move
      TZ: 'America/Argentina/Buenos_Aires'
      CRON: '0 3 * * *'
      CRON_ABORT: '0 6 * * *'
      UID: ${PUID}
      GID: ${PGID}
      FORCE_SYNC: ${FORCE_SYNC}
    networks:
      - main

networks:
  main:
    external: true

    
