version: '2'

services:
  movies-downstream:
    image: pfidr/rclone:latest
    container_name: movies-downstream
    restart: unless-stopped
    volumes:
      - "${STORAGE_LOCATION}/radarr/movies:/destination"
      - "${RCLONE_CONFIG}:/config"
      - "/root/.ssh:/.ssh:ro"
      - "${RCLONE_CONFIG}/logs_movies:/tmp/"
    environment:
      SYNC_SRC: DanteConePlex:${REMOTE_STORAGE_LOCATION}/radarr/movies
      SYNC_DEST: /destination
      SYNC_OPTS: '-v --min-age 90d --delete-empty-src-dirs'
      CHECK_URL: https://hc-ping.com/98faf6af-1722-4e39-8d5f-5f2eb6f8bb34
      RCLONE_CMD: move
      TZ: 'America/Argentina/Buenos_Aires'
      CRON: '0 3 * * 0'
      CRON_ABORT: '0 12 * * 0'
    networks:
      - main

  series-downstream:
    image: pfidr/rclone:latest
    container_name: series-downstream
    restart: unless-stopped
    volumes:
      - "${STORAGE_LOCATION}/sonarr/tvseries:/destination"
      - "${RCLONE_CONFIG}:/config"
      - "/root/.ssh:/.ssh:ro"
      - "${RCLONE_CONFIG}/logs_series:/tmp/"
    environment:
      SYNC_SRC: DanteConePlex:${REMOTE_STORAGE_LOCATION}/sonarr/tvseries
      SYNC_DEST: /destination
      SYNC_OPTS: '-v --min-age 90d --delete-empty-src-dirs'
      CHECK_URL: https://hc-ping.com/0b507d80-79fb-4b61-a211-227c11c98909
      RCLONE_CMD: move
      TZ: 'America/Argentina/Buenos_Aires'
      CRON: '0 3 * * 1'
      CRON_ABORT: '0 12 * * 1'
    networks:
      - main

networks:
  main:
    external: true

    