version: '2'

services:
  movies-downstream:
    image: pfidr/rclone:latest
    container_name: movies-downstream
    restart: unless-stopped
    volumes:
      - "${STORAGE_LOCATION}/radarr/movies:/destination"
      - "${CONFIG_LOCATION}/rclone:/config"
      - "/root/.ssh:/.ssh:ro"
      - "${CONFIG_LOCATION}/rclone/logs_movies:/tmp/"
    environment:
      SYNC_SRC: DanteConePlex:${REMOTE_STORAGE_LOCATION}/radarr/movies
      SYNC_DEST: /destination
      SYNC_OPTS: '-v --min-age 30d --delete-empty-src-dirs'
      CHECK_URL: https://hc-ping.com/98faf6af-1722-4e39-8d5f-5f2eb6f8bb34
      RCLONE_DIR_CHECK_SKIP: 'true'
      RCLONE_CMD: move
      TZ: 'America/Argentina/Buenos_Aires'
      CRON: '0 3 * * *'
      CRON_ABORT: '0 12 * * *'
      UID: ${PUID}
      GID: ${PGID}
    networks:
      - main

  series-downstream:
    image: pfidr/rclone:latest
    container_name: series-downstream
    restart: unless-stopped
    volumes:
      - "${STORAGE_LOCATION}/sonarr/tvseries:/destination"
      - "${CONFIG_LOCATION}/rclone:/config"
      - "/root/.ssh:/.ssh:ro"
      - "${CONFIG_LOCATION}/rclone/logs_series:/tmp/"
    environment:
      SYNC_SRC: DanteConePlex:${REMOTE_STORAGE_LOCATION}/sonarr/tvseries
      SYNC_DEST: /destination
      SYNC_OPTS: '-v --min-age 30d --delete-empty-src-dirs'
      CHECK_URL: https://hc-ping.com/0b507d80-79fb-4b61-a211-227c11c98909
      RCLONE_DIR_CHECK_SKIP: 'true'
      RCLONE_CMD: move
      TZ: 'America/Argentina/Buenos_Aires'
      CRON: '0 3 * * *'
      CRON_ABORT: '0 15 * * *'
      UID: ${PUID}
      GID: ${PGID}
    networks:
      - main

  music-downstream:
    image: pfidr/rclone:latest
    container_name: music-downstream
    restart: unless-stopped
    volumes:
      - "${STORAGE_LOCATION}/deezldr/music:/destination"
      - "${CONFIG_LOCATION}/rclone:/config"
      - "/root/.ssh:/.ssh:ro"
      - "${CONFIG_LOCATION}/rclone/logs_music:/tmp/"
    environment:
      SYNC_SRC: DanteConePlex:${REMOTE_STORAGE_LOCATION}/deezldr/music
      SYNC_DEST: /destination
      SYNC_OPTS: '-v --min-age 30d --delete-empty-src-dirs'
      RCLONE_DIR_CHECK_SKIP: 'true'
      CHECK_URL: 'https://hc-ping.com/5610a3b0-f036-41d0-8a3d-260b2b4b57ce'
      RCLONE_CMD: move
      TZ: 'America/Argentina/Buenos_Aires'
      CRON: '0 3 * * *'
      CRON_ABORT: '0 15 * * *'
      UID: ${PUID}
      GID: ${PGID}
    networks:
      - main

networks:
  main:
    external: true

    