version: '3.3'
services:
  cupsd:
    image: olbat/cupsd
    container_name: cupsd
    privileged: true
    restart: unless-stopped
    volumes:
      - /var/run/dbus:/var/run/dbus
    ports:
      - 631:631