version: '3.3'

services:
  cloudprint:
    image: tianon/google-cloud-print-connector
    container_name: cloudprint
    user: 1000:1000
    volumes:
      - /var/run/dbus:/var/run/dbus:ro
      - ${CONFIG_LOCATION}/cloudprint:/config
    network_mode: host
    command: "gcp-cups-connector --log-to-console"
    working_dir: /config