version: '3.3'

services:
  cloudprint:
    image: jaymoulin/google-cloudprint
    container_name: cloudprint
    privileged: true
    restart: unless-stopped
    environment:
      TZ: America/Argentina/Buenos_Aires
      CUPS_USER_ADMIN: ${CUPS_USER_ADMIN}
      CUPS_USER_PASSWORD: ${CUPS_USER_PASSWORD}
    volumes:
      - /dev/bus/usb:/dev/bus/usb
    ports:
      - 631:631
    