version: '3.3'

services:
  cupsd:
    image: thbe/cups
    container_name: cupsd
    privileged: true
    restart: unless-stopped
    cap_add:
      - SYS_ADMIN
    ports:
      # - 137:137/udp
      # - 139:139/tcp
      # - 445:445/tcp
      - 631:631/tcp
      # - 5353:5353/udp
    environment:
      TZ: America/Argentina/Buenos_Aires
      container: docker
      CUPS_ENV_PASSWORD: ${CUPS_USER_PASSWORD}
      CUPS_ENV_DEBUG: 'true'
      CUPS_ENV_HOST: papini.local
    volumes:
      - /dev/bus/usb:/dev/bus/usb
      - ${CONFIG_LOCATION}/cloudprint/cupsd:/etc/cups/
    