version: '3.3'

services:
  google-cloudprint:
    image: jaymoulin/google-cloudprint
    container_name: google-cloudprint
    privileged: true
    restart: unless-stopped
    environment:
      CUPS_USER_ADMIN: ${CUPS_USER_ADMIN}
      CUPS_USER_PASSWORD: ${CUPS_USER_PASSWORD}
    volumes:
      - /dev/bus/usb:/dev/bus/usb
      - ${CONFIG_LOCATION}/cloudprint/.cloudprintauth.json:/root/.cloudprintauth.json
    ports:
      - 631:631
    