version: '2'

services:
  filebrowser:
    container_name: filebrowser
    image: filebrowser/filebrowser
    restart: unless-stopped
    volumes:
      - ${FILEBROWSER_HOME}:/srv
      - ${FILEBROWSER_CONFIG}/database.db:/database.db
      - ${FILEBROWSER_CONFIG}:/etc/filebrowser
    labels:
      - "traefik.docker.network=main"
      - "traefik.enable=true"
      - "traefik.basic.frontend.rule=Host:cloud.${DOMAIN_URL}"
      - "traefik.basic.port=80"
      - "traefik.basic.protocol=http"
      - "traefik.backend.healthcheck.path=/"
      - "traefik.backend.healthcheck.interval=30s"
    networks:
      - main

networks: 
  main:
    external: true


