version: '2'

services:
  filebrowser:
    container_name: filebrowser
    image: filebrowser/filebrowser
    restart: unless-stopped
    volumes:
      - ${FILEBROWSER_HOME}:/srv
      - ${CONFIG_LOCATION}/filebrowser/database.db:/database.db
      - ${CONFIG_LOCATION}/filebrowser:/etc/filebrowser
    labels:
      - "traefik.docker.network=main"
      - "traefik.enable=true"
      - "traefik.basic.frontend.rule=Host:cloud.${DOMAIN_URL}"
      - "traefik.basic.port=80"
      - "traefik.frontend.entryPoints=http,https"
      - "traefik.backend.healthcheck.path=/"
      - "traefik.backend.healthcheck.interval=30s"
      - "traefik.frontend.auth.forward.address=${OAUTH_FORWARD_URL}"
      - "traefik.frontend.auth.forward.authResponseHeaders=X-Forwarded-User"
      - "traefik.frontend.auth.forward.trustForwardHeader=true"
    networks:
      - main

networks: 
  main:
    external: true


