version: '3'

services:
  spotify-ripper-web:
    image: dantebarba/spotify-ripper-web:0.1.0
    container_name: spotify-ripper-web
    environment:
      user: ${SPOTIFY_USER}
      pass: ${SPOTIFY_PASS}
      SPOTIPY_CLIENT_ID: ${SPOTIFY_CLIENT_ID}
      SPOTIPY_CLIENT_SECRET: ${SPOTIFY_CLIENT_SECRET}
      SPOTIPY_REDIRECT_URI: http://www.purple.com
      STOP_AFTER: 35m
      TZ: ${DOCKER_TZ}
    volumes:
      - "${SPOTIFY_RIPPER_CONFIG}:/config"
      - ${STORAGE_LOCATION}/spotify-ripper/music:/music

  spotify-cron:
    image: dantebarba/whatsmyhealth
    container_name: spotify-cron
    restart: unless-stopped
    environment:
      CHECK_URL: ${SPOTIFY_CRON_CHECK}
      TZ: ${DOCKER_TZ}
      CRON: ${CRON}
      TEST_URL: 'http://spotify-ripper-web:5000/api/v1/${SPOTIFY_PLAYLIST}'
      LOG_LEVEL: ${LOG_LEVEL}
      FORCE_TEST: ${FORCE_TEST}
    volumes:
    - $CONFIG_LOCATION/spotify-cron:/tmp/
