version: '2'

services:
  speedtest:
    image: adolfintel/speedtest:latest
    container_name: speedtest
    labels:
      - "traefik.enable=true"
      - "traefik.port=80"
      - "traefik.backend=speedtest"
      - "traefik.frontend.entryPoints=http,https"
      - "traefik.frontend.rule=Host:speedtest.${DOMAIN_URL}"
      - traefik.frontend.headers.frameDeny=false
      - traefik.frontend.headers.browserXSSFilter=true
      - traefik.frontend.headers.STSSeconds=315360000
      - traefik.frontend.headers.forceSTSHeader=false
      - traefik.frontend.headers.contentTypeNosniff=true
    networks:
      - main

networks:
  main:
    external: true