version: '2'  
  
services:
  load-balancer:
    image: traefik:v1.7.11
    container_name: load-balancer
    restart: unless-stopped
    command:
      - "--acme"
      - "--acme.storage=acme.json"
      - "--acme.entryPoint=https"
      - "--acme.dnsChallenge.provider=cloudflare"
      - "--acme.dnsChallenge.delaybeforecheck=300"
      - "--acme.domains=${DOMAIN_URL}"
      - "--acme.onHostRule=true"
      - "--acme.acmelogging=true"
      - "--acme.email=${ACME_EMAIL}"
      - "--docker"
      - "--docker.domain=${DOMAIN_URL}"
      - "--docker.exposedbydefault=false"
      - "--docker.watch=true"
    ports:
      - "80:80"
      - "443:443"
    environment:
      - CF_API_EMAIL=${CLOUDFLARE_EMAIL}
      - CF_API_KEY=${CLOUDFLARE_API_KEY}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${STORAGE_LOCATION}/traefik:/etc/traefik
      - ./traefik.toml:/traefik.toml
      - ./acme.json:/acme.json
    networks:
      - main
      - default
    labels:
      - "traefik.enable=true"
      - "traefik.port=8080"
      - "traefik.backend=traefik"
      - "traefik.docker.network=main"
      - "traefik.frontend.entryPoints=http,https"
      - "traefik.frontend.rule=Host:traefik.${DOMAIN_URL}"

  traefik-forward-auth:
      image: thomseddon/traefik-forward-auth:2.1.0
      container_name: traefik-forward-auth
      environment:
        PROVIDERS_GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
        PROVIDERS_GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
        OIDC_ISSUER: ${OIDC_ISSUER}
        SECRET: secret_key
        AUTH_HOST: ${AUTH_HOST}
        COOKIE_DOMAIN: ${COOKIE_DOMAINS}
      networks:
        - main
        - default
      labels:
        - "traefik.docker.network=main"
        - "traefik.enable=true"
        - "traefik.basic.frontend.rule=Host:auth.dantebarba.com.ar"
        - "traefik.basic.port=4181"
        - "traefik.frontend.entryPoints=http,https"
        - "traefik.frontend.auth.forward.address=http://traefik-forward-auth:4181"
        - "traefik.frontend.auth.forward.trustForwardHeader=true"

networks:
  main:
    external: true
  default:
    driver: bridge