version: '2'

services:
  load-balancer:
    image: traefik:v1.7.11
    container_name: load-balancer
    restart: always
    ports:
      - "80:80"
      - "443:443"
      - "5050:5050"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik.toml:/traefik.toml
      - ${TRAEFIK_CONFIG}/acme.json:/acme.json
    networks:
      - main

networks:
  main:
    external: true
