version: '2'

services:
  load-balancer:
    image: traefik:v1.7.11
    container_name: load-balancer
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${TRAEFIK_CONFIG}:/etc/traefik
      - ./traefik.toml:/traefik.toml
    networks:
      - main
      - default
    labels:
      - "traefik.enable=true"
      - "traefik.port=8080"
      - "traefik.backend=traefik"
      - "traefik.frontend.rule=Host:traefik.${DOMAIN_URL}"
      - "traefik.docker.network=main"

networks:
  main:
    external: true
  default:
    driver: bridge
