debug = true
logLevel = "INFO" #DEBUG, INFO, WARN, ERROR, FATAL, PANIC

defaultEntryPoints = ["http"]
[api]

[entryPoints]
  [entryPoints.http]
  address = ":80"

[docker]
domain = "papini.lan"
watch = true
exposedByDefault = false