debug = true
logLevel = "INFO" #DEBUG, INFO, WARN, ERROR, FATAL, PANIC

defaultEntryPoints = ["http"]

[web]
# Port for the status/dashboard page
address = ":5001"


[entryPoints]
  [entryPoints.http]
  address = ":80"

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "papini.lan"
watch = true
exposedByDefault = false