debug = true
logLevel = "INFO" #DEBUG, INFO, WARN, ERROR, FATAL, PANIC

defaultEntryPoints = ["http", "https"]

[web]
# Port for the status/dashboard page
address = ":5050"
dashboard = true


[entryPoints]
    [entryPoints.http]
    address = ":80"
        [entryPoints.http.redirect]
        entryPoint = "https"

    [entryPoints.https]
    address = ":443"
    [entryPoints.https.tls]

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "papini.lan"
watch = true
exposedByDefault = false

[acme]
email = "dantebarba@gmail.com"
storage = "acme.json"
entryPoint = "https"
onHostRule = true
[acme.httpChallenge]
    entryPoint = "http"