version: '3.3'

services:
  vfs-server:
    image: linuxserver/openssh-server:latest
    container_name: vfs-server
    restart: unless-stopped
    volumes:
      - ${STORAGE_LOCATION}/radarr/movies/local:/movies
      - ${STORAGE_LOCATION}/transmission/downloads/complete:/downloads
      - ${CONFIG_LOCATION}/vfs_server:/config
    environment:
      PGID: ${PGID}
      PUID: ${PUID}
      TZ: America/Argentina/Buenos_Aires
      USER_NAME: ${VFS_USERNAME}
      USER_PASSWORD: ${VFS_PASSWORD}
      SUDO_ACCESS: 'false'
      PASSWORD_ACCESS: 'true'
    labels:
      - "traefik.docker.network=main"
      - "traefik.enable=true"
      - traefik.backend=vfs
      - "traefik.basic.frontend.rule=Host:vfs.${DOMAIN_URL}"
      - "traefik.basic.port=80"
      - "traefik.frontend.entryPoints=http,https"
      - "traefik.frontend.headers.SSLRedirect=true"
      - traefik.frontend.auth.forward.address=${OAUTH_FORWARD_URL}
      - traefik.frontend.auth.forward.authResponseHeaders=X-Forwarded-User
      - traefik.frontend.auth.forward.trustForwardHeader=true
    networks:
      - main

networks:
  main:
    external: true