version: '3.3'  

services:
  timemachine:
    container_name: timemachine
    image: mbentley/timemachine:smb
    envinronment:
      CUSTOM_SMB_CONFIG: false
      CUSTOM_USER: false
      MIMIC_MODEL: TimeCapsule8,119
      EXTERNAL_CONF: ""
      HIDE_SHARES: "no"
      TM_USERNAME: "timemachine"
      TM_PASSWORD: ${TIMEMACHINE_PASSWORD}
      TM_UID: 1000
      TM_GID: 1000
      SET_PERMISSIONS: false
      SHARE_NAME: TimeMachine
      SMB_PORT: 445
      VOLUME_SIZE_LIMIT: "0"
      WORKGROUP: WORKGROUP
    volumes:
      - ${STORAGE_LOCATION}/timemachine:/opt/timemachine
      - ${CONFIG_LOCATION}/timemachine/samba:/var/lib/samba
      - ${CONFIG_LOCATION}/timemachine/cache:/var/cache/samba
      - ${CONFIG_LOCATION}/timemachine/run:/run/samba
    networks:
      - timemachinevlan

networks:
  timemachinevlan:
      driver: macvlan
      driver_opts:
        parent: ${TIMEMACHINE_VLAN_PARENT}
      ipam:
        config:
          - subnet: 192.168.0.0/24
          - gateway: 192.168.0.1
          - ip_range: 192.168.0.99/32