version: '3.3'  

services:
  timemachine:
    container_name: timemachine
    hostname: papini.local
    image: mbentley/timemachine:smb
    environment:
      CUSTOM_SMB_CONFIG: "false"
      CUSTOM_USER: "false"
      MIMIC_MODEL: TimeCapsule8,119
      EXTERNAL_CONF: ""
      HIDE_SHARES: "no"
      TM_USERNAME: "timemachine"
      TM_PASSWORD: ${TIMEMACHINE_PASSWORD}
      TM_UID: 1000
      TM_GID: 1000
      SET_PERMISSIONS: "false"
      SHARE_NAME: TimeMachine
      SMB_PORT: 445
      VOLUME_SIZE_LIMIT: "0"
      WORKGROUP: WORKGROUP
    volumes:
      - ${STORAGE_LOCATION}/timemachine:/opt/timemachine
      - ${CONFIG_LOCATION}/timemachine/samba:/var/lib/samba
      - ${CONFIG_LOCATION}/timemachine/cache:/var/cache/samba
      - ${CONFIG_LOCATION}/timemachine/run:/run/samba
    networks:
      timemachinevlan:
        ipv4_address: 192.168.0.99

networks:
  timemachinevlan:
      driver: macvlan
      driver_opts:
        parent: ${TIMEMACHINE_VLAN_PARENT}
      ipam:
        config:
          - subnet: 192.168.0.0/24