version: '2'

services:
  steamcmd:
    container_name: steamcmd
    image: dantebarba/steamcmd-hlds:latest
    restart: unless-stopped
    volumes:
      - "./server.cfg:/home/steam/hlds/cstrike/server.cfg"
      - "./liblist.gam:/home/steam/hlds/cstrike/liblist.gam"
      - "./dproto.cfg:/home/steam/hlds/cstrike/dproto.cfg"
      - "./addons:/home/steam/hlds/cstrike/addons"
    ports:
      - 27015:27015/tcp
      - 27015:27015/udp