version: '2'

services:
  steamcmd:
    container_name: steamcmd
    image: dantebarba/steamcmd-hlds:latest
    restart: unless-stopped
    volumes:
      - "./server.cfg:/home/steam/hlds/cstrike/server.cfg"
    ports:
      - 27015:27015/tcp
      - 27015:27015/udp