version: '3.3'

services:
  apcupsd:
    image: gersilex/apcupsd
    restart: unless-stopped
    hostname: ${HOSTNAME}
    privileged: true
    container_name: apcupsd
    environment:
      TZ: ${DOCKER_TZ}
      APCUPSD_MAIL: mail
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - "./mailwrapper.sh:/usr/local/sbin/mail"
      - "/etc/localtime:/etc/localtime:ro"
      - "/tmp/apcupsd-docker:/tmp/apcupsd-docker"
      - "./apcupsd.conf:/etc/apcupsd/apcupsd.conf"