version: '3.3'

services:
  apcupsd:
    image: gersilex/apcupsd
    privileged: true
    container_name: apcupsd
    environment:
      - TZ: America/Argentina/Buenos_Aires
    volumes:
      - "/tmp/apcupsd-docker:/tmp/apcupsd-docker"
      - "./apcupsd.conf:/etc/apcupsd/apcupsd.conf"