version: '3.3'

services:
  nessus:
    image: stevemcgrath/nessus_scanner:latest
    container_name: nessus
    ports:
      - 8834:8834
    environment:
      LICENSE: ${NESSUS_LICENSE}
      SCANNER_NAME: ${NESSUS_SCANNER_NAME}
    volumes:
      - nessus:/opt/nessus
    labels:
      - "traefik.docker.network=main"
      - "traefik.enable=true"
      - "traefik.basic.frontend.rule=Host:nessus.${DOMAIN_URL}"
      - "traefik.basic.port=8834"
      - "traefik.frontend.entryPoints=https"
    networks:
      - main

volumes:
  nessus:

networks:
  main:
    external: true
