version: '2'

services:
  nas-health-status:
    image: dantebarba/whatsmyhealth
    container_name: nas-health-status
    restart: unless-stopped
    environment:
      CHECK_URL: 'https://hc-ping.com/6aea44fe-22d1-4652-85ee-fe0757f41a0e'
      TZ: ${DOCKER_TZ}
      CRON: '0,30 * * * *'
      LOG_LEVEL: '7'
      FORCE_TEST: '1'
    volumes:
    - $CONFIG_LOCATION/healthcheck:/tmp/
