version: '3.7'

services:
  nas-health-status:
    image: dantebarba/whatsmyhealth
    container_name: nas-health-status
    restart: unless-stopped
    environment:
      CHECK_URL: ${CHECK_URL}
      TZ: ${DOCKER_TZ}
      CRON: ${HEALTHCHECK_CRON}
      LOG_LEVEL: ${LOG_LEVEL}
      FORCE_TEST: ${FORCE_TEST}
    volumes:
    - $CONFIG_LOCATION/healthcheck:/tmp/