version: '2'

services:
  nas-health-status:
    image: dantebarba/whatsmyhealth
    container_name: nas-health-status
    restart: unless-stopped
    environment:
      CHECK_URL: 'https://hc-ping.com/6aea44fe-22d1-4652-85ee-fe0757f41a0e'
      TZ: 'America/Argentina/Buenos_Aires'
      CRON: '0,30 * * * *'
      LOG_LEVEL: '7'
      FORCE_SYNC: '1'
    volumes:
    - $HEALTHCHECK_CONFIG:/tmp/
