version: '3.7'

services:
  plexdrive:
    image: rclone/rclone:latest
    container_name: plexdrive
    restart: unless-stopped
    command: "mount gdrive-lb: /mnt/movies --config=/config/rclone/rclone.conf --allow-other --gid ${PGID} --uid ${PUID} --buffer-size 256M --log-level ${LOG_LEVEL} --stats 2m --use-mmap --dir-cache-time 72h --poll-interval 2m --read-only"
    volumes:
      - ${CONFIG_LOCATION}/gdrive:/config/rclone
      - /mnt/movies:/mnt/movies:shared
    privileged: true
    devices:
      - /dev/fuse
    cap_add:
      - MKNOD
      - SYS_ADMIN
    environment:
      PGID: ${PGID}
      PUID: ${PUID}
      LOG_LEVEL: ${LOG_LEVEL}
      TZ: ${DOCKER_TZ}
    labels:
      - "group=storage"

