version: '3.3'

services:
  twitter-archive:
    image: nginx:latest
    container_name: twitter-archive
    volumes:
      - ${STORAGE_LOCATION}/twitter.app:/usr/share/nginx/html:ro
    environment:
      - NGINX_HOST=twitter.${DOMAIN_URL}
      - NGINX_PORT=80
    labels:
      - "traefik.docker.network=main"
      - "traefik.enable=true"
      - "traefik.basic.frontend.rule=Host:twitter.${DOMAIN_URL}"
      - "traefik.basic.port=80"
      - "traefik.frontend.entryPoints=http,https"
      - "traefik.frontend.headers.SSLRedirect=true"
    networks:
      - main

networks:
  main:
    external: true