version: '3.3'

services:
  twitter-archive:
    image: nginx:alpine
    container_name: twitter-archive
    volumes:
      - ${STORAGE_LOCATION}/twitter.app:/usr/share/nginx/html:ro
    environment:
      - NGINX_HOST=twitter.${DOMAIN_URL}
      - NGINX_PORT=80
      - TZ=${DOCKER_TZ}
    labels:
      - "traefik.docker.network=main"
      - "traefik.enable=true"
      - "traefik.basic.frontend.rule=Host:twitter.${DOMAIN_URL}"
      - "traefik.basic.port=80"
      - "traefik.frontend.entryPoints=http,https"
      - "traefik.frontend.headers.SSLRedirect=true"
      - traefik.frontend.auth.forward.address=${OAUTH_FORWARD_URL}
      - traefik.frontend.auth.forward.authResponseHeaders=X-Forwarded-User
      - traefik.frontend.auth.forward.trustForwardHeader=true
    networks:
      - main

networks:
  main:
    external: true