version: '2'

services:
  transmission:
    extends: 
      file: ${DOCKER_MEDIA_SERVER}/docker-compose.yml
      service: transmission
    labels:
      - "traefik.docker.network=main"
      - "traefik.enable=true"
      - "traefik.basic.frontend.rule=Host:transmission.${DOMAIN_URL}"
      - "traefik.basic.port=9091"
      - "traefik.frontend.entryPoints=http,https"
    networks:
      - main
  jackett:
    extends: 
      file: ${DOCKER_MEDIA_SERVER}/docker-compose.yml
      service: jackett
    labels:
      - "traefik.docker.network=main"
      - "traefik.enable=true"
      - "traefik.basic.frontend.rule=Host:jackett.${DOMAIN_URL}"
      - "traefik.basic.port=9117"
      - "traefik.frontend.entryPoints=http,https"
    networks:
      - main
  plex:
    extends: 
      file: ${DOCKER_MEDIA_SERVER}/docker-compose.yml
      service: plex
    labels:
      - "traefik.docker.network=main"
      - "traefik.enable=true"
      - "traefik.basic.frontend.rule=Host:plex.${DOMAIN_URL}"
      - "traefik.basic.port=32400"
      - "traefik.frontend.entryPoints=http,https"
      - "traefik.backend.healthcheck.path=/web/index.html"
      - "traefik.backend.healthcheck.interval=30s"
    volumes:
      - "${STORAGE_LOCATION}/plex:/config"
      - "${STORAGE_LOCATION}/sonarr/tvseries:/tv"
      - "${STORAGE_LOCATION}/radarr/movies:/movies"
      - "${STORAGE_LOCATION}/deezldr/music:/music"
      - "${STORAGE_LOCATION}/plex:/transcode"
      - "${FILEBROWSER_HOME}:/home"
    networks:
      - main
  sonarr:
    extends: 
      file: ${DOCKER_MEDIA_SERVER}/docker-compose.yml
      service: sonarr
    labels:
      - "traefik.docker.network=main"
      - "traefik.enable=true"
      - "traefik.basic.frontend.rule=Host:sonarr.${DOMAIN_URL}"
      - "traefik.basic.port=8989"
      - "traefik.frontend.entryPoints=http,https"
      - "traefik.backend.healthcheck.path=/api/system/status?apikey=${SONARR_API_KEY}"
      - "traefik.backend.healthcheck.interval=30s"
    networks:
      - main
      
  radarr:
    extends: 
      file: ${DOCKER_MEDIA_SERVER}/docker-compose.yml
      service: radarr
    labels:
      - "traefik.docker.network=main"
      - "traefik.enable=true"
      - "traefik.basic.frontend.rule=Host:radarr.${DOMAIN_URL}"
      - "traefik.basic.port=7878"
      - "traefik.frontend.entryPoints=http,https"
      - "traefik.backend.healthcheck.path=/api/system/status?apikey=${RADARR_API_KEY}"
      - "traefik.backend.healthcheck.interval=30s"
    networks:
      - main

  deezldr:
    extends: 
      file: ${DOCKER_MEDIA_SERVER}/docker-compose.yml
      service: deezldr
    labels:
      - "traefik.docker.network=main"
      - "traefik.enable=true"
      - "traefik.basic.frontend.rule=Host:music.dantebarba.com.ar"
      - "traefik.basic.port=1730"
      - "traefik.frontend.entryPoints=http,https"
    networks:
      - main


networks:
  main:
    external: true