version: '2'

services:
  transmission:
    extends: 
      file: ${DOCKER_MEDIA_SERVER}/docker-compose.yml
      service: transmission
    environment:
      - TZ=${DOCKER_TZ}
    labels:
      - "traefik.docker.network=main"
      - "traefik.enable=true"
      - "traefik.basic.frontend.rule=Host:transmission.${DOMAIN_URL}"
      - "traefik.basic.port=9091"
      - "traefik.frontend.entryPoints=http,https"
      - traefik.frontend.auth.forward.address=${OAUTH_FORWARD_URL}
      - traefik.frontend.auth.forward.authResponseHeaders=X-Forwarded-User
      - traefik.frontend.auth.forward.trustForwardHeader=true
    networks:
      - main

  radarr:
    image: "linuxserver/radarr"
    container_name: radarr
    hostname: radarr
    restart: unless-stopped
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "${STORAGE_LOCATION}/radarr/config:/config"
      - ${STORAGE_LOCATION}:/docker
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${DOCKER_TZ}
      - VIRTUAL_HOST=radarr.${DOMAIN_URL}
    labels:
      - "traefik.docker.network=main"
      - "traefik.enable=true"
      - "traefik.basic.frontend.rule=Host:radarr.${DOMAIN_URL}"
      - traefik.backend=radarr
      - "traefik.basic.port=7878"
      - "traefik.frontend.entryPoints=http,https"
      - traefik.frontend.auth.forward.address=${OAUTH_FORWARD_URL}
      - traefik.frontend.auth.forward.authResponseHeaders=X-Forwarded-User
      - traefik.frontend.auth.forward.trustForwardHeader=true
    networks:
      - main

  sonarr:
    image: "linuxserver/sonarr"
    container_name: sonarr
    hostname: sonarr
    restart: unless-stopped
    volumes:
     - "/etc/localtime:/etc/localtime:ro"
     - "${STORAGE_LOCATION}/sonarr/config:/config"
     - "${STORAGE_LOCATION}:/docker"
    environment:
     - PUID=${PUID}
     - PGID=${PGID}
     - VIRTUAL_HOST=sonarr.${DOMAIN_URL}
     - TZ=${DOCKER_TZ}
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=main"
      - "traefik.port=8989"
      - "traefik.backend=sonarr"
      - "traefik.frontend.entryPoints=http,https"
      - "traefik.frontend.rule=Host:sonarr.${DOMAIN_URL}"
      - traefik.frontend.auth.forward.address=${OAUTH_FORWARD_URL}
      - traefik.frontend.auth.forward.authResponseHeaders=X-Forwarded-User
      - traefik.frontend.auth.forward.trustForwardHeader=true
    networks:
      - main


  plex:
    extends: 
      file: ${DOCKER_MEDIA_SERVER}/docker-compose.yml
      service: plex
    labels:
      - "traefik.docker.network=main"
      - "traefik.enable=true"
      - "traefik.basic.frontend.rule=Host:plex.${DOMAIN_URL}"
      - "traefik.basic.port=32400"
      - "traefik.frontend.entryPoints=http,https"
      - "traefik.backend.healthcheck.path=/web/index.html"
      - "traefik.backend.healthcheck.interval=30s"
    volumes:
      - "${STORAGE_LOCATION}/plex:/config"
      - "${STORAGE_LOCATION}/sonarr/tvseries:/tv"
      - "${STORAGE_LOCATION}/radarr/movies:/movies"
      - "${STORAGE_LOCATION}/deemix/music:/music"
      - "${STORAGE_LOCATION}/plex:/transcode"
      - "/mnt/movies:/mnt/movies"
      - "${FILEBROWSER_HOME}:/home"
    networks:
      - main

networks:
  main:
    external: true