version: '2'

services:
  transmission:
    extends: 
      file: ${DOCKER_MEDIA_SERVER}/docker-compose.yml
      service: transmission
    environment:
      - TZ=America/Argentina/Buenos_Aires
    labels:
      - "traefik.docker.network=main"
      - "traefik.enable=true"
      - "traefik.basic.frontend.rule=Host:transmission.${DOMAIN_URL}"
      - "traefik.basic.port=9091"
      - "traefik.frontend.entryPoints=http,https"
      - traefik.frontend.auth.forward.address=${OAUTH_FORWARD_URL}
      - traefik.frontend.auth.forward.authResponseHeaders=X-Forwarded-User
      - traefik.frontend.auth.forward.trustForwardHeader=true
    networks:
      - main

  radarr:
    image: "linuxserver/radarr"
    container_name: radarr
    hostname: radarr
    restart: unless-stopped
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "${STORAGE_LOCATION}/radarr/config:/config"
      - "${STORAGE_LOCATION}/radarr/movies:/movies"
      - ${STORAGE_LOCATION}/library/movies:/4k
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=America/Argentina/Buenos_Aires
      - VIRTUAL_HOST=radarr.${DOMAIN_URL}
    labels:
      - "traefik.docker.network=main"
      - "traefik.enable=true"
      - "traefik.basic.frontend.rule=Host:radarr.${DOMAIN_URL}"
      - traefik.backend=radarr
      - "traefik.basic.port=7878"
      - "traefik.frontend.entryPoints=http,https"
      - traefik.frontend.auth.forward.address=${OAUTH_FORWARD_URL}
      - traefik.frontend.auth.forward.authResponseHeaders=X-Forwarded-User
      - traefik.frontend.auth.forward.trustForwardHeader=true
    networks:
      - main

  sonarr:
    image: "linuxserver/sonarr"
    container_name: sonarr
    hostname: sonarr
    restart: unless-stopped
    volumes:
     - "/etc/localtime:/etc/localtime:ro"
     - "${STORAGE_LOCATION}/sonarr/config:/config"
     - "${STORAGE_LOCATION}/sonarr/tvseries:/tv"
     - "${STORAGE_LOCATION}/transmission/downloads:/downloads"
    environment:
     - PUID=${PUID}
     - PGID=${PGID}
     - VIRTUAL_HOST=sonarr.${DOMAIN_URL}
     - TZ=America/Argentina/Buenos_Aires
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=main"
      - "traefik.port=8989"
      - "traefik.backend=sonarr"
      - "traefik.frontend.entryPoints=http,https"
      - "traefik.frontend.rule=Host:sonarr.${DOMAIN_URL}"
      - traefik.frontend.auth.forward.address=${OAUTH_FORWARD_URL}
      - traefik.frontend.auth.forward.authResponseHeaders=X-Forwarded-User
      - traefik.frontend.auth.forward.trustForwardHeader=true
    networks:
      - main


  plex:
    extends: 
      file: ${DOCKER_MEDIA_SERVER}/docker-compose.yml
      service: plex
    labels:
      - "traefik.docker.network=main"
      - "traefik.enable=true"
      - "traefik.basic.frontend.rule=Host:plex.${DOMAIN_URL}"
      - "traefik.basic.port=32400"
      - "traefik.frontend.entryPoints=http,https"
      - "traefik.backend.healthcheck.path=/web/index.html"
      - "traefik.backend.healthcheck.interval=30s"
    volumes:
      - "${STORAGE_LOCATION}/plex:/config"
      - "${STORAGE_LOCATION}/sonarr/tvseries:/tv"
      - "${STORAGE_LOCATION}/radarr/movies:/movies"
      - "${STORAGE_LOCATION}/deezldr/music:/music"
      - "${STORAGE_LOCATION}/plex:/transcode"
      - "${FILEBROWSER_HOME}:/home"
    networks:
      - main

  syncarr:
      image: syncarr/syncarr:latest
      container_name: syncarr
      restart: unless-stopped
      volumes:
        - "${STORAGE_LOCATION}/radarr/movies:/movies"
      environment:
        RADARR_A_URL: ${RADARR_URL}
        RADARR_A_KEY: ${REMOTE_RADARR_API_KEY}
        RADARR_B_URL: http://radarr:7878
        RADARR_B_KEY: ${LOCAL_RADARR_API_KEY}
        RADARR_B_PROFILE: Any
        RADARR_B_PATH: /movies
        SYNCARR_AUTO_SEARCH: 0
        SYNC_INTERVAL_SECONDS: 300
        TZ: America/Argentina/Buenos_Aires
      networks:
        - main
    
  syncarr-sonarr:
      image: syncarr/syncarr:latest
      container_name: syncarr-sonarr
      restart: unless-stopped
      volumes:
        - ${STORAGE_LOCATION}/sonarr/tvseries:/tv
      environment:
        SONARR_A_URL: ${SONARR_URL}
        SONARR_A_KEY: ${REMOTE_SONARR_API_KEY}
        SONARR_B_URL: http://sonarr:8989
        SONARR_B_KEY: ${LOCAL_SONARR_API_KEY}
        SONARR_B_PROFILE: Any
        SONARR_B_PATH: /tv
        SYNCARR_AUTO_SEARCH: 0
        SYNC_INTERVAL_SECONDS: 300
        TZ: America/Argentina/Buenos_Aires
      networks:
        - main

networks:
  main:
    external: true