version: '3.3'

services:
  rclone-vfs:
    image: rclone/rclone:latest
    container_name: rclone-vfs
    restart: unless-stopped
    privileged: true
    command: mount Crown:/root/docker /vfs --dir-perms 777 --file-perms 777  --gid ${PGID} --uid ${PUID} --allow-other --buffer-size 32M --poll-interval 1m --log-file=/config/rclone/logs_vfs/rclone-movies.log --log-level=DEBUG
    volumes:
      - "${STORAGE_LOCATION}/rclone-vfs/vfs:/vfs:shared"
      - "${CONFIG_LOCATION}/rclone:/config/rclone"
      - "${CONFIG_LOCATION}/rclone/ssh:/.ssh:ro"
    environment:
      PHP_TZ: America/Argentina/Buenos_Aires
      PUID: 1000
      PGID: 1000
    devices:
      - /dev/fuse
    cap_add:
      - SYS_ADMIN
